# Generated by Django 5.0.1 on 2024-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='max_redemptions',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='redemptions',
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='redemption_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='redemption_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
