# Generated by Django 5.0.1 on 2024-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_management', '0002_remove_voucher_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='redemption_limit',
        ),
        migrations.AddField(
            model_name='voucher',
            name='redemption_limit_choice',
            field=models.CharField(choices=[('single', 'Single Redemption'), ('multiple', 'Multiple Redemption'), ('x_times', 'X times Redemption')], default='single', max_length=20),
        ),
    ]
