# Generated by Django 5.0.1 on 2024-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_management', '0004_rename_redemption_limit_choice_voucher_redemption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='redemption_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
