# Generated by Django 5.0.1 on 2024-01-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voucher_management', '0002_remove_voucher_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher_management.voucher')),
            ],
        ),
    ]
